function bindGallery($, galleryId, photos) {

    $('#' + galleryId).bind('click', function(event) {

        // this prevents the link from navigating to #
        event.preventDefault();

        Lightview.show(photos, { controls: 'thumbnails' });

    });
}

var wedddingDayOfficialPhotos = [
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-004.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-007.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-019.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-024.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-033.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-034.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-041.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-042.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-046.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-047.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-053.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-055.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-064.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-066.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-072.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-076.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-086.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-104.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-110.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-115.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-130.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-132.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-145.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-155.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-163.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-167.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-172.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-175.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-179.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-182.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-185.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-187.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-189.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-190.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-193.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-194.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-202.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-208.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-222.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-226.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-230.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-244.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-250.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-252.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-255.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-256.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-260.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-261.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-270.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-278.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-290.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-295.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-296.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-298.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-300.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-313.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-324.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-330.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-336.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-337.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-347.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-348.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-349.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-350.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-352.jpg'},
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/wedding-day-official/Armstrong-290314-353.jpg'}
];

var honeymoonDay1Photos = [
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/louiseandpatrick.com/honeymoon-day-1/2014-03-31_12_23_03.jpg', caption: 'More champagne?! Why not! What a great way to start our honeymoon!', title: 'Caviar House & Prunier Seafood Bar' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/2014-03-31_18_12_53.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/IMG_8649.jpg', caption: 'A rather jet lagged sleepy Pat about to enjoy our first Japanese cuisine', title: 'Shiodome City Center' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/IMG_8651.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/IMG_8656.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/IMG_8657.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/IMG_8659.jpg', caption: 'The first of many many vending machines! Hot and cold coffee!!', title: 'Tokyo, Japan' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/IMG_8660.jpg', caption: 'Plastic dinner anyone?!', title: 'Tokyo, Japan' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/IMG_8668.jpg', caption: 'Real dinner!', title: 'Shiodome City Center' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-1/IMG_8670.jpg', caption: 'More vending machines - with beer and Slat (Lou\'s favourite evening tipple)', title: 'Hotel Villa Fontaine Shiodome' }
];

var honeymoonDay2Photos = [
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5046.jpg', title: 'Meiji Jingu Shrine' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5048.jpg', caption: 'Sake barrels' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5057.jpg', caption: 'Waiting for the Emperor!', title: 'Meiji Jingu Shrine' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5058.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5061.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5081.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5084.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5096.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5112.jpg', caption: 'Blossom celebrations' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5117.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5129.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5134.jpg', caption: 'The horizontal flame - used to be vertical but local residents complained it was blocking their view!' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5143.jpg', caption: 'Cat cafe - a Japanese craze. Why have a pet when you can borrow one for an hour at a time', title: 'Cafe Calaugh' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5153.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5158.jpg', caption: 'Shaking for my fortune' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5161.jpg', caption: 'hurray it was a good one!!' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMAG0233.jpg', caption: 'Shabu shabu - like a Japanese fondue (kind of)' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5167.jpg', title: 'Odaiba' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-2/IMG_5182.jpg', caption: 'Enjoying dinner with a view', title: 'Gonpachi' }
];

var honeymoonDay3Photos = [
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_5193.jpg', caption: 'Queuing for sushi at 5am', title: 'Tsukiji Fish Market' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_5194.jpg', caption: 'Only on my honeymoon would I force the husband to get up at 4am to go to a fish market. We got there at 4.30am... and that was too late!', title: 'Tsukiji Fish Market' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_8679.jpg', caption: 'European and Japanese plastic breakfast samples... yes, they\'re plastic!', title: 'Hotel Villa Fontaine Shiodome.' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_8684.jpg', caption: 'Rainy day in Electric City', title: 'Akihabara, (Electric City), Tokyo' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_5205.jpg', caption: 'Pat learning to play Pachinko. I was the only woman in the whole place!', title: 'Akihabara, (Electric City), Tokyo' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_8689.jpg', title: 'Akihabara, (Electric City), Tokyo' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_8694.jpg', caption: 'Slightly tricky to find but Ivan\'s Ramen was well worth the hunt - thank you Katherine and Gordon Lau!', title: 'Setagaya-ku, Tokyo, Japan' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_8691.jpg', caption: 'Ordering dinner!', title: 'Setagaya-ku, Tokyo, Japan' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_5210.jpg', title: 'Setagaya-ku, Tokyo, Japan' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-3/IMG_5211.jpg', caption: 'The best ramen in Japan!', title: 'Setagaya-ku, Tokyo, Japan' },
];

var honeymoonDay4_6Photos = [
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8700.jpg', caption: 'Finally the rain turned to snow!', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8701.jpg', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8709.jpg', caption: 'Lunchtime snoozle', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8710.jpg', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8711.jpg', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8714.jpg', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8718.jpg', caption: 'Far more interesting than your standard European skiing fare', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8722.jpg', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8726.jpg', caption: 'Lost in translation! At a neighbouring hotel for our first experience of onsen.', title: 'Hakuba Alpine Hotel, Hakuba' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8729.jpg', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8733.jpg', caption: 'Our only non-Japanese meal of the holiday (but it was still amazing Japanese beef!)', title: 'Hakuba Resort Hotel La Neige Higashikan' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8736.jpg', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8739.jpg', caption: 'When in Rome. ;-) The Japanese love their power-naps!' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8740.jpg', caption: 'Pat at the start of the 1998 Nagano Winter Olympics Downhill!', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8742.jpg', caption: 'Pat still at the start of the 1998 Nagano Winter Olympics Downhill!', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8750.jpg', caption: 'Sake and real ale on the slopes', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8751.jpg', caption: '\'Spring\' skiing!!', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8753.jpg' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8760.jpg', caption: 'Apres ski - hot wine and hot sake - perfect for the \'spring\' skiing!', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_8762.jpg', caption: 'Not the most lively apres ski but think we were a little late in the season!', title: 'Hakuba Happo-One Winter Resort' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-days-4-6/IMG_5221.jpg', caption: 'Friendliest hotel ever! La Neige Honken in Hakuba', title: 'Hakuba Happo-One Winter Resort' }
];

var honeymoonDay7Photos = [
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5226.jpg', title: 'Hakuba, Nagano, Japan' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5233.jpg', caption: 'On route to Nagano', title: 'Hakuba, Nagano, Japan' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5248.jpg', title: 'Nagano, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5249.jpg', title: 'Nagano, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5251.jpg', title: 'Nagano, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5258.jpg', caption: 'Bento!', title: 'Nagano, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5259.jpg', caption: 'More plastic food!', title: 'Nagano, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5260.jpg', title: 'Zenko-ji Temple, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5261.jpg', title: 'Zenko-ji Temple, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5263.jpg', title: 'Zenko-ji Temple, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5266.jpg', title: 'Zenko-ji Temple, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5269.jpg', title: 'Zenko-ji Temple, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5271.jpg', title: 'Zenko-ji Temple, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5273.jpg', title: 'Zenko-ji Temple, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5288.jpg', caption: 'Turtle!', title: 'Zenko-ji Temple, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5292.jpg', title: 'Nagano, Nagano' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5297.jpg', caption: 'We were really getting into our trainspotting... this was Lou\'s favourite...', title: 'Nagano Station' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5299.jpg', caption: '... mainly because the driver went up in this hatch to his cabin. Just missed photographing him!', title: 'Nagano Station' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5307.jpg', title: 'Nagano Station' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5312.jpg', caption: 'Our ryokan - a traditional Japanese inn. Green tea and a heated blanket to greet us!', title: 'Kokuya Ryokan, Yudanaka' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_5313.jpg', caption: 'And our very own zen garden!', title: 'Kokuya Ryokan, Yudanaka' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_8770.jpg', caption: 'Kaiseki - Japanese haute cuisine', title: 'Kokuya Ryokan, Yudanaka' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_8781.jpg', title: 'Kokuya Ryokan, Yudanaka' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_8774.jpg', caption: 'Hot plum shochu', title: 'Kokuya Ryokan, Yudanaka' },
    { url: 'http://res.cloudinary.com/de4f9sf2c/image/upload/c_scale,h_612/louiseandpatrick.com/honeymoon-day-7/IMG_8779.jpg', title: 'Kokuya Ryokan, Yudanaka' }
];
